Rewrite of the rclone mount for a rclone webdav.

diff --git a/rclone-webdav/rootfs/etc/cont-finish.d/20-unmount b/rclone-webdav/rootfs/etc/cont-finish.d/20-unmount
--- a/rclone-webdav/rootfs/etc/cont-finish.d/20-unmount
+++ b/rclone-webdav/rootfs/etc/cont-finish.d/20-unmount
@@ -14,14 +14,14 @@ s6-svwait -D /var/run/s6/services/*
 #awk '/efsgoogle:/ && /\'$ENVIRON["MountPoint"]'/ {print; exit 1}' /proc/mounts
 
 #check if rclone gracefully unmounted
-if grep -Eq ''$RemotePath'.*'$MountPoint'|'$MountPoint'.*'$RemotePath'' /proc/mounts; then
-    echo -e "${PREFFIX} ${Red}force unmounting with fusermount $UnmountCommands at: $(date +%Y.%m.%d-%T)${Color_Off}"
-    fusermount $UnmountCommands $MountPoint
-    wait ${!}
-    exit 1
-else
-    #cleanup of mount namespace
-    umount $MountPoint
-    echo -e "${PREFFIX} ${Green}successful unmounted${Color_Off}"
-    exit 0
-fi
+#if grep -Eq ''$RemotePath'.*'$MountPoint'|'$MountPoint'.*'$RemotePath'' /proc/mounts; then
+#    echo -e "${PREFFIX} ${Red}force unmounting with fusermount $UnmountCommands at: $(date +%Y.%m.%d-%T)${Color_Off}"
+#    fusermount $UnmountCommands $MountPoint
+#    wait ${!}
+#    exit 1
+#else
+#    #cleanup of mount namespace
+#    umount $MountPoint
+#    echo -e "${PREFFIX} ${Green}successful unmounted${Color_Off}"
+#    exit 0
+#fi
